name: flutter_app
description: Demo App using the BLoC pattern.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  meta: '>=1.1.0 <2.0.0'
  flutter_redux: ^0.5.3
  redux_logging: ^0.3.0
  http: ^0.12.0+2
  dio: ^2.1.16
  path_provider: ^1.3.0
  collection: 1.14.11
  cupertino_icons: ^0.1.2
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.3+4
  flutter_slidable: ^0.5.3
  material_design_icons_flutter: ^3.2.4096
  sqflite: ^1.1.6+4
  common_utils: ^1.1.3
  keyboard_avoider: ^0.1.2
  flutter_launcher_icons: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter



#flutter_icons:
#  image_path: assets/icons/icon.png
#  android: "ic_launcher"
#  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: PTSans
    fonts:
      - asset: fonts/PTSans-Regular.ttf
      - asset: fonts/PTSans-RegularItalic.ttf
      - style: italic
  - family: PTSansBold
    fonts:
      - asset: fonts/PTSans-Bold.ttf
      - asset: fonts/PTSans-BoldItalic.ttf
      - weight: 700