name: flutter_app
description: Demo App using the BLoC pattern.
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  package_resolver: ^1.0.10
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

fonts:
  - family: PTSans
    fonts:
      - asset: fonts/PTSans-Regular.ttf
      - asset: fonts/PTSans-RegularItalic.ttf
      - style: italic
  - family: PTSansBold
    fonts:
      - asset: fonts/PTSans-Bold.ttf
      - asset: fonts/PTSans-BoldItalic.ttf
      - weight: 700